import { MakeupProduct } from "./types";

export const ALL_PRODUCTS_CATALOG: MakeupProduct[] = [
  {
    id: "prod_1",
    name: "Batom Matte Ruby Woo",
    brand: "MAC Cosmetics",
    type: "Batom Matte",
    barcode: "773602120011",
    primarySeason: "inverno_frio",
    compatibleSeasons: ["inverno_frio", "inverno_brilhante", "inverno_escuro"],
    colors: ["#C41E3A"],
    description: "Vermelho azulado ultra-mate vibrante. Possui alta saturação e temperatura puramente fria.",
    parameters: { temp: "Fria", intensity: "Brilhante", depth: "Média" }
  },
  {
    id: "prod_2",
    name: "Blush Orgasm",
    brand: "NARS",
    type: "Blush Compacto",
    barcode: "607845040132",
    primarySeason: "primavera_clara",
    compatibleSeasons: ["primavera_clara", "primavera_quente", "outono_suave"],
    colors: ["#F3A297", "#DF7A6E"],
    description: "Rosa pêssego iluminado com partículas de brilho dourado. Perfeito para peles quentes e radiantes de Primavera.",
    parameters: { temp: "Quente", intensity: "Brilhante/Radiante", depth: "Clara" }
  },
  {
    id: "prod_3",
    name: "Batom Liquido Bruna",
    brand: "Linha Bruna Tavares",
    type: "Batom Líquido",
    barcode: "7898588523001",
    primarySeason: "inverno_brilhante",
    compatibleSeasons: ["inverno_brilhante", "inverno_frio", "primavera_brilhante"],
    colors: ["#D21F3C"],
    description: "Vermelho vivo puríssimo e opaco, com subtons azulados e alta definição de contraste.",
    parameters: { temp: "Fria", intensity: "Brilhante", depth: "Média" }
  },
  {
    id: "prod_4",
    name: "Base Fit Me 120 Claro Cálido",
    brand: "Maybelline NY",
    type: "Base Facial",
    barcode: "041554533431",
    primarySeason: "primavera_quente",
    compatibleSeasons: ["primavera_quente", "primavera_clara", "outono_quente"],
    colors: ["#F3D0B5"],
    description: "Base fluida mate com fundo levemente amarelado/pêssego, ideal para peles com subtom quente.",
    parameters: { temp: "Quente", intensity: "Suave", depth: "Clara" }
  },
  {
    id: "prod_5",
    name: "Batom Líquido Niina Secrets Hermione",
    brand: "Eudora / Niina Secrets",
    type: "Batom Líquido",
    barcode: "7891033481231",
    primarySeason: "outono_suave",
    compatibleSeasons: ["outono_suave", "verao_suave", "outono_quente"],
    colors: ["#B38B82"],
    description: "Malva acinzentado terroso sutil, com fundo quente suave. Ideal para cartelas de baixa saturação.",
    parameters: { temp: "Neutra-Quente", intensity: "Macia/Suave", depth: "Média-Escura" }
  },
  {
    id: "prod_6",
    name: "Gloss Volumão Copacabana",
    brand: "Quem Disse, Berenice?",
    type: "Gloss Labial",
    barcode: "7891034010502",
    primarySeason: "primavera_clara",
    compatibleSeasons: ["primavera_clara", "verao_claro", "primavera_quente"],
    colors: ["#FFA39E"],
    description: "Tom pêssego translúcido com microesferas de brilho delicado, realça peles claras e luminosas.",
    parameters: { temp: "Neutra-Quente", intensity: "Brilhante", depth: "Clara" }
  },
  {
    id: "prod_7",
    name: "Contorno Facial Stick Taupe",
    brand: "Mari Maria Makeup",
    type: "Contorno Stick",
    barcode: "7898651811228",
    primarySeason: "verao_suave",
    compatibleSeasons: ["verao_suave", "outono_suave", "verao_frio"],
    colors: ["#C2B2A3"],
    description: "Marrom acinzentado de tom frio e opaco. Fantástico para criar sombras naturais sem amarelar.",
    parameters: { temp: "Fria", intensity: "Suave", depth: "Média" }
  },
  {
    id: "prod_8",
    name: "Sombra Cremosa Paint Pot Groundwork",
    brand: "MAC Cosmetics",
    type: "Sombra de Olhos",
    barcode: "773602196621",
    primarySeason: "outono_suave",
    compatibleSeasons: ["outono_suave", "outono_quente", "outono_escuro"],
    colors: ["#8B7E74"],
    description: "Taupe neutro opaco e macio de profundidade média. Um clássico elegante de calmaria terrosa.",
    parameters: { temp: "Neutra-Quente", intensity: "Suave", depth: "Média" }
  },
  {
    id: "prod_9",
    name: "Blush Stick Peach",
    brand: "Bruna Tavares",
    type: "Blush Stick",
    barcode: "7898588529997",
    primarySeason: "primavera_quente",
    compatibleSeasons: ["primavera_quente", "primavera_clara", "outono_quente"],
    colors: ["#FFA07A"],
    description: "Rosa pêssego solar acolhedor com toque avelulado, harmoniza lindamente com peles vivas e ricas.",
    parameters: { temp: "Quente", intensity: "Brilhante", depth: "Média" }
  },
  {
    id: "prod_10",
    name: "Batom Mate Velvet Teddy",
    brand: "MAC Cosmetics",
    type: "Batom Mate",
    barcode: "773602334814",
    primarySeason: "outono_quente",
    compatibleSeasons: ["outono_quente", "outono_suave", "primavera_quente"],
    colors: ["#C4977E"],
    description: "Nude bege clássico, sutilmente quente e aveludado. Enquadra-se majestosamente em peles douradas.",
    parameters: { temp: "Quente", intensity: "Suave", depth: "Média" }
  },
  {
    id: "prod_11",
    name: "Batom Líquido Mate Diva",
    brand: "MAC Cosmetics",
    type: "Batom Mate",
    barcode: "773602120158",
    primarySeason: "inverno_escuro",
    compatibleSeasons: ["inverno_escuro", "outono_escuro", "inverno_frio"],
    colors: ["#5C1324"],
    description: "Burgundy escuro e dramático. Subtons vinhos frios de profunda sofisticação.",
    parameters: { temp: "Fria", intensity: "Suave", depth: "Escura" }
  },
  {
    id: "prod_12",
    name: "Lápis de Boca Boldly Bare",
    brand: "MAC Cosmetics",
    type: "Lápis Labial",
    barcode: "773602058420",
    primarySeason: "outono_suave",
    compatibleSeasons: ["outono_suave", "primavera_clara", "outono_quente"],
    colors: ["#E29B7F"],
    description: "Nude pêssego acastanhado levemente rosado, sutilmente quente e extremamente maleável.",
    parameters: { temp: "Neutra-Quente", intensity: "Suave", depth: "Média" }
  },
  {
    id: "prod_13",
    name: "Batom Super Stay Vinil Ink Coy",
    brand: "Maybelline NY",
    type: "Batom Líquido",
    barcode: "041554085428",
    primarySeason: "verao_claro",
    compatibleSeasons: ["verao_claro", "verao_suave", "verao_frio"],
    colors: ["#D48C9E"],
    description: "Rosa malva delicado de brilho vinilizado. Perfeito para realçar a luminosidade fresca e suave de peles de Verão.",
    parameters: { temp: "Fria", intensity: "Brilhante", depth: "Clara" }
  },
  {
    id: "prod_14",
    name: "Blush Líquido Soft Pinch Happy",
    brand: "Rare Beauty",
    type: "Blush Líquido",
    barcode: "840122302401",
    primarySeason: "verao_frio",
    compatibleSeasons: ["verao_frio", "verao_claro", "inverno_frio"],
    colors: ["#FA7FA5"],
    description: "Rosa radiante de tom frio e acabamento luminoso. Harmoniza perfeitamente com peles de Verão e Inverno.",
    parameters: { temp: "Fria", intensity: "Brilhante", depth: "Clara" }
  }
];
